environment:
  # Set your VSTS Personal Access Token to facilitate publishing
  # Don't store it in the clear, encrypt it: https://ci.appveyor.com/tools/encrypt
  VSTS_PAT:
    secure: 2BNyamlNkZa6SXn1sM9glmE47eVLL8FGBhzm8TXdJycz29VmQZt2xGQjQCbL9f1xFZzsBznDZhFf6GV4BbhNJg==

install:
  # Install the TFX Command Line Interface
  npm i -g tfx-cli

before_build:
  - ps: .\SyncCommon.ps1

build_script:
  tfx extension publish --manifest-globs vss-extension.json --auth-type 'pat' --token '%VSTS_PAT%' --overrides {"version":"%APPVEYOR_BUILD_NUMBER%"}"

artifacts:
  - path: ./*.vsix
    name: vsts-btdf-tasks

version: 0.0.{build}